-- Phase 2 migration: user accounts, private analysis history, admin override.
-- Run in Supabase SQL editor.

-- Required for case-insensitive email handling.
create extension if not exists citext;

-- User profile table.
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email citext unique not null,
    role text not null default 'user' check (role in ('user', 'admin')),
    last_seen_at timestamptz,
    created_at timestamptz not null default timezone('utc', now())
);

-- Analysis history table scoped per user.
create table if not exists public.analyses (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    user_email citext not null,
    total_revenue numeric not null default 0,
    total_costs numeric not null default 0,
    total_profit numeric not null default 0,
    avg_margin numeric not null default 0,
    health_score integer not null default 0,
    health_label text not null default '',
    best_month text not null default '',
    worst_month text not null default '',
    alerts_count integer not null default 0,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists analyses_user_id_idx on public.analyses(user_id);
create index if not exists analyses_created_at_idx on public.analyses(created_at desc);
create index if not exists profiles_role_idx on public.profiles(role);

-- Enable RLS.
alter table public.profiles enable row level security;
alter table public.analyses enable row level security;

-- Keep policies idempotent.
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
drop policy if exists "profiles_insert_self" on public.profiles;
drop policy if exists "profiles_update_own_or_admin" on public.profiles;
drop policy if exists "analyses_select_own_or_admin" on public.analyses;
drop policy if exists "analyses_insert_own_or_admin" on public.analyses;
drop policy if exists "analyses_update_own_or_admin" on public.analyses;
drop policy if exists "analyses_delete_own_or_admin" on public.analyses;

-- Profiles policies.
create policy "profiles_select_own_or_admin"
on public.profiles
for select
to authenticated
using (
    id = auth.uid()
    or exists (
        select 1
        from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
    )
);

create policy "profiles_insert_self"
on public.profiles
for insert
to authenticated
with check (
    id = auth.uid()
    or exists (
        select 1
        from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
    )
);

create policy "profiles_update_own_or_admin"
on public.profiles
for update
to authenticated
using (
    id = auth.uid()
    or exists (
        select 1
        from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
    )
)
with check (
    id = auth.uid()
    or exists (
        select 1
        from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
    )
);

-- Analyses policies.
create policy "analyses_select_own_or_admin"
on public.analyses
for select
to authenticated
using (
    user_id = auth.uid()
    or exists (
        select 1
        from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
    )
);

create policy "analyses_insert_own_or_admin"
on public.analyses
for insert
to authenticated
with check (
    user_id = auth.uid()
    or exists (
        select 1
        from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
    )
);

create policy "analyses_update_own_or_admin"
on public.analyses
for update
to authenticated
using (
    user_id = auth.uid()
    or exists (
        select 1
        from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
    )
)
with check (
    user_id = auth.uid()
    or exists (
        select 1
        from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
    )
);

create policy "analyses_delete_own_or_admin"
on public.analyses
for delete
to authenticated
using (
    user_id = auth.uid()
    or exists (
        select 1
        from public.profiles p
        where p.id = auth.uid() and p.role = 'admin'
    )
);

-- Trigger: auto-create profile rows when users sign up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, email, role, created_at)
    values (
        new.id,
        coalesce(new.email, ''),
        case
            when coalesce(new.email, '') = any(string_to_array(coalesce(current_setting('app.admin_emails', true), ''), ','))
            then 'admin'
            else 'user'
        end,
        timezone('utc', now())
    )
    on conflict (id) do update
    set email = excluded.email;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Seed or update your admin users by email (edit values before running).
update public.profiles
set role = 'admin'
where lower(email::text) in (
    'vwanheda@gmail.com'
);
